### ISSUE TITLE
Consider deprecating?

### ISSUE THREAD

**Issue by ekryski** [duythinht/passport-token-auth#1]
In order to reduce confusion in npm, would you consider deprecating this lib in favour of https://github.com/leepowellcouk/passport-token, https://github.com/joaquimserafim/json-web-token or https://github.com/jaredhanson/passport-http-bearer?

**Comment by duythinht** [comment]
It was deprecated on npm.

**Comment by ekryski** [comment]
Hmm. That's actually how I found it. On the npm site.

![screen shot 2015-03-26 at 9 27 51 am](https://cloud.githubusercontent.com/assets/599019/6849721/83cc9c8c-d39a-11e4-94dd-9ec6475adc42.png)

Maybe an issue with npm or it's not actually deprecated?

**Comment by ekryski** [comment]
I also did a quick search using `npm search passport-auth-token` and it's not marked as deprecated.

```
$ npm search passport-token-auth
NAME                DESCRIPTION                                      AUTHOR     DATE       VERSION KEYWORDS
passport-token-auth HTTP Token authentication strategy for Passport. =duythinht 2015-03-26 0.1.2   passport auth authn authentication authz authorization http bearer token oauth
```

**Comment by duythinht** [comment]
You will have notice when install this module, like this:

    $ npm install npm install passport-token-auth
    npm WARN deprecated passport-token-auth@0.1.2: Shutdown project

But on npmjs.org site, they do not mark as deprecated, I think it was a problem on npmjs.
I will consider to unpublish, but It's not recommender
https://docs.npmjs.com/cli/unpublish

    It is generally considered bad behavior to remove versions of a library that others are depending on!

    Consider using the deprecate command instead, if your intent is to encourage users to upgrade.
